### ISSUE TITLE
HyperV provider support for macOS boxes

### ISSUE THREAD

**Issue by mcandre** [elliotweiser/ansible-osx-command-line-tools#16]
Hiya, thank you for publishing Vagrant boxes for macOS! Would it be possible to offer HyperV provided boxes as well? Unfortunately, Docker in Windows relies on HyperV these days, and HyperV is unable to run concurrently with the VirtualBox hypervisor. In other words, developers working with Windows hosts must choose to boot with either HyperV enabled to run Docker, or else HyperV disabled to run VirtualBox and Vagrant. But if the macOS Vagrant boxes were integrated with the HyperV provider, then Windows users would be able to hack on Docker and Vagrant projects at the same time, without having to constantly reboot. What do you think?

**Comment by elliotweiser** [comment]
You're welcome. I've been meaning to update those and expand provider coverage with Packer (instead of the hacky way I built them last time).

Hypothetically speaking, are you proposing running MacOS VMs on a Windows host?

**Comment by elliotweiser** [comment]
If that is your proposition (and it sounds like it is), I don't think I can condone it. Hyper-V is native virtualization for Windows systems. 

https://www.vagrantup.com/docs/hyperv/
https://en.wikipedia.org/wiki/Hyper-V

Running MacOS virtually on non-MacOS hardware or with non-MacOS base operating system is explicitly forbidden by the MacOS ULA(s).

http://images.apple.com/legal/sla/docs/macOS1013.pdf
http://images.apple.com/legal/sla/docs/macOS1012.pdf
http://images.apple.com/legal/sla/docs/OSX1011.pdf
http://images.apple.com/legal/sla/docs/OSX10103.pdf

Section 2B, iii, states that the license agreement only permits you:

> (iii) to install, use and run up to two (2) additional copies or instances of the Apple Software within virtual operating system environments on each Mac Computer you own or control that is already running the Apple Software, for purposes of: (a) software development; (b) testing during software development; (c) using macOS Server; or (d) personal, non-commercial use.

Alas, to work on MacOS-based projects, you'll need to do it on Apple-provided hardware. Fortunately, Docker for Mac and Virtualbox play well together.
