### ISSUE TITLE
Check for Command Line Tools in Software Update list hangs occasionally 

### ISSUE THREAD

**Issue by SurferL** [elliotweiser/ansible-osx-command-line-tools#18]
It seems that the step Check for Command Line Tools in Software Update list occasionally hangs and therefore breaks the build.

Could be something to do with this? https://apple.stackexchange.com/questions/82551/mac-app-store-update-stuck-installing-calculating

Is there anyway I can work around this, perhaps by adding a retry after x time?

Linked from https://github.com/geerlingguy/ansible-role-homebrew/issues/86

**Comment by elliotweiser** [comment]
@SurferL What are your Mac OS and Ansible versions?

That's an interesting suggestion/observation re: the stack exchange post. I can start digging into that.

You're welcome to add a retry feature to help mitigate some of your build time woes. I'll look into it myself as well at some point, but I can't make any promises as to when that'll be. If you'd like to propose a PR for adding that feature, I'll review it.

**Comment by SurferL** [comment]
Hey @elliotweiser ,

I'm using macOS Sierra Version 10.12.6, and Ansible version 2.4.1.0

I was thinking of using a retry feature but wasn't sure how to do it just yet

**Comment by elliotweiser** [comment]
Since this hasn't been a problem for some time, I'm going to close this. I was experimenting with timeouts before, but the level of effort didn't seem to justify the feature. Plus we can't control the performance/reliability of Apple's softwareupdate servers.

Feel free to ping me if you think this issue has re-surfaced.
