### ISSUE TITLE
Ansible Galaxy project renamed?

### ISSUE THREAD

**Issue by mindrunner** [elliotweiser/ansible-osx-command-line-tools#39]
This error recectly occured:

elliotweiser.osx-command-line-tools was NOT installed successfully: - sorry, elliotweiser.osx-command-line-tools was not found on https://galaxy.ansible.com.

Using  elliotweiser.osx_command_line_tools works fine. Was this renamed on purpose?

Other projects, like geerlingguy.mas fail as well, because they use this as a dependency.

**Comment by elliotweiser** [comment]
No, I didn't rename it on purpose.

Ansible Galaxy went through a major re-design some time over the last few days. As a result, user names and roles with dashes in their names were impacted. There are a number of open issues reported on this, some of them by me. 

I even tried to release geerlingguy.homebrew version 2.4.3 (which addresses the underscore problem), but the Notifications API is broken as well. 

https://github.com/ansible/galaxy/issues/775
https://github.com/ansible/galaxy/issues/776

That's just a taste. They have plenty of post-upgrade issues to work through.

**Comment by mindrunner** [comment]
Cool, thanks. I suppose, we can close this.
