### ISSUE TITLE
Unable to find Command Line Tools in Software Update list on macOS Mojave 10.14.5 

### ISSUE THREAD

**Issue by luissilvaos** [elliotweiser/ansible-osx-command-line-tools#51]
Hi guys,

I'm trying to run this role in the new macOS Mojave 10.14.5 but the task `Check for Command Line Tools in Software Update list` keeps failing. Also, its preceding tasks `Is the C++ compiler useable?` and `Check the Command Line Tools package metadata` are failing too.

Do you guys have any clue on this?

Thanks

**Comment by elliotweiser** [comment]
@luissilvaos That is actually normal behavior if the command line tools hasn't already been installed. The role ignores those errors and uses that information to determine that it needs to install them. Please shared output here so we can discuss further.

**Comment by luissilvaos** [comment]
@elliotweiser Thanks for the response. Yes, the preceding tasks are failing as expected, since I'm running the role on a clean macOS. However, the task that is supposed to validate if the Command Line Tools are available in the Software Update list is failing since in this new macOS version the `softwareupdate -l` command is returning the following message `No new software available.`.

**Comment by luissilvaos** [comment]
Also, I just ran the role on a clean macOS Mojave 10.14.2 and the role worked as expected. It seems that something has changed in the most recent macOS Mojave versions.

**Comment by elliotweiser** [comment]
Related: https://github.com/Homebrew/brew/issues/6215

**Comment by elliotweiser** [comment]
Apple appears to have fixed the problem on their side.
