### ISSUE TITLE
Why is it necessary to check? That also pop-up a unwanted dialog

### ISSUE THREAD

**Issue by senguttuvang** [elliotweiser/ansible-osx-command-line-tools#62]
I don't know the purpose of gcc check but it fails and brings up a pop-up in the target Mac system. Is it expected behavior?

![image](https://user-images.githubusercontent.com/1772791/91253288-1a83e080-e77d-11ea-9e24-dd11ff1ecf2a.png)

![image](https://user-images.githubusercontent.com/1772791/91253328-2ec7dd80-e77d-11ea-971d-8dd91ebe32d4.png)

**Comment by elliotweiser** [comment]
Hmm. I don't recall this behavior happening at any point up to OS X 10.14 (Mojave). Is this on Catalina? Can you share some details about your target OS version?

**Comment by senguttuvang** [comment]
Yes, that's Catalina with latest update (10.5.6)

**Comment by elliotweiser** [comment]
I haven't gotten around to adding catalina support just yet, and there have been some reports of other weird issues when running this role on OS X 10.15.+. There will need to be some investigation to fully add this support.

**Comment by jdumas** [comment]
FYI I'm also experiencing this issue on Big Sur (macOS 11.2.3).

**Comment by jdumas** [comment]
According to [this SO answer](https://stackoverflow.com/questions/15371925/how-to-check-if-command-line-tools-is-installed), we should use the following to check for command line tools:
```
xcode-select -p
```

**Comment by elliotweiser** [comment]
Hi @jdumas. Last time I messed with this, that would also spawn the unwanted dialogue. I haven't had much time to test this on Big Sur. Feel free to submit a PR if you believe this is a better/more appropriate way to test the presence of the CLI tools.
