### ISSUE TITLE
Task 'Install Command Line Tools' failed because of undefined 'su_list' variable on macos 10.15

### ISSUE THREAD

**Issue by dennyweiss** [elliotweiser/ansible-osx-command-line-tools#63]
```
elliotweiser/ansible-osx-command-line-tools: 73acd94056c5b2305d59d3f8708a56740a959c61
ansible: 2.9.4
  config file = /Users/d/.macos-provisioning/ansible.cfg
  configured module search path = ['/Users/d/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/d/.macos-provisioning/.venv/python-venv-3.7.7/lib/python3.7/site-packages/ansible
  executable location = /Users/d/.macos-provisioning/.venv/python-venv-3.7.7/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
MacOS: 10.15.6 (19G2021)
Command Line Tools: v11,5 (29.05.20, 06:02)
```

A playbook run errored out at task 'Install Command Line Tools' with message 'su_list' is undefined (tasks/main.yaml:89). After digging deeper into task 'Check for Command Line Tools in Software Update list (MacOS >= 10.15).' i found out that 

```
set -o pipefail; softwareupdate -l | grep -B 1 -E 'Command Line Tools'
```

returned with an unexpected non zero exit code. 

## ~~Solution one~~ Approach one: Silence the breaking error in task 'Install Command Line Tools' 

```tasks/main.yaml:91
when: (su_list is defined) and (pkg_info.rc != 0 or compiler.rc != 0 or not clt.stat.exists)
```

But then i somehow realised that something is wrong with my current macos 10.15 installation. *(System was created from scratch but the current user is imported from macos 10.14 Time Machine backup)* 
An inspection of `/Library/Developer/CommandLineTools` revealed that the SDK 10.14 was used as default instead of 10.15 which led to the described error.

## Final solution: Clean up CommandLineTools installation

1. Uninstall all Command Line Tools
2. Reset default Command Line Tools
3. Reboot
4. Install Command Line Tools from scratch

```sh
sudo -rm /Library/Developer/CommandLineTools
sudo xcode-select -r
sudo shutdown -r now
# after reboot
git # in order to trigger ui installation of Command Line Tools
```

**Comment by dennyweiss** [comment]
@elliotweiser Issue can be closed because `elliotweiser/ansible-osx-command-line-tools` only revealed an issue with the underlying misconfigured system but i find it valuable to share the insight

**Comment by elliotweiser** [comment]
Thanks for sharing. This remind me of a similar issue from a while back. Let me see if I can find it.

**Comment by elliotweiser** [comment]
I didn't find an exact match for this situation, but it reminds me of something I have definitely seen before. Did you happen to capture any stdout or stderr from your earlier attempt?

**Comment by dennyweiss** [comment]
@elliotweiser Sorry i don't have any error logs, but with macOS Big Sur approaching... who knows. I think you can close this issue.
